const hospitalData = {
    "基隆市": [
        { "name": "衛生福利部基隆醫院", "district": "信義區", "address": "信二路268號" },
        { "name": "長庚醫療財團法人基隆長庚紀念醫院", "district": "安樂區", "address": "麥金路222號" },
        { "name": "三軍總醫院-正榮院區", "district": "中正區", "address": "正榮街100號" },
        { "name": "三軍總醫院-孝二院區", "district": "仁愛區", "address": "孝二路39號" },
        { "name": "仁祥診所", "district": "仁愛區", "address": "忠一路20號" },
        { "name": "臺灣礦工醫院", "district": "暖暖區", "address": "源遠路29號" },
        { "name": "新昆明醫院", "district": "中正區", "address": "中正路30號" },
        { "name": "基隆市立醫院", "district": "信義區", "address": "東信路282號" }
    ],
    "臺北市": [
        { "name": "國立臺灣大學醫學院附設醫院-總院區（東址）", "district": "中正區", "address": "中山南路7號" },
        { "name": "國立臺灣大學醫學院附設醫院-總院區（西址）", "district": "中正區", "address": "常德街1號" },
        { "name": "國立臺灣大學醫學院附設醫院-兒童醫院", "district": "中正區", "address": "中山南路8號" },
        { "name": "國立臺灣大學醫學院附設醫院-癌醫中心", "district": "大安區", "address": "基隆路三段155巷57號" },
        { "name": "國立臺灣大學醫學院附設醫院-北護分院", "district": "萬華區", "address": "內江街87號" },
        { "name": "三軍總醫院-內湖總院", "district": "內湖區", "address": "成功路二段325號" },
        { "name": "三軍總醫院-汀州院區", "district": "中正區", "address": "汀州路三段40號" },
        { "name": "臺北榮民總醫院", "district": "北投區", "address": "石牌路二段201號" },
        { "name": "國泰綜合醫院-臺北總院", "district": "大安區", "address": "仁愛路四段280號" },
        { "name": "長庚醫療財團法人台北長庚紀念醫院", "district": "松山區", "address": "敦化北路199號" },
        { "name": "馬偕紀念醫院-臺北總院", "district": "中山區", "address": "中山北路二段92號" },
        { "name": "新光吳火獅紀念醫院", "district": "士林區", "address": "文昌路95號" },
        { "name": "臺北市立萬芳醫院", "district": "文山區", "address": "興隆路三段111號" },
        { "name": "基督復臨安息日會醫療財團法人臺安醫院", "district": "松山區", "address": "八德路二段424號" },
        { "name": "三軍總醫院松山分院附設民眾診療服務處", "district": "松山區", "address": "健康路131號" },
        { "name": "臺北醫學大學附設醫院", "district": "信義區", "address": "吳興街252號" },
        { "name": "臺北市立聯合醫院-仁愛院區", "district": "大安區", "address": "仁愛路四段10號" },
        { "name": "臺北市立聯合醫院-中興院區", "district": "大同區", "address": "鄭州路145號" },
        { "name": "臺北市立聯合醫院-婦幼院區", "district": "中正區", "address": "福州街12號" },
        { "name": "臺北市立聯合醫院-和平院區", "district": "中正區", "address": "中華路二段33號" },
        { "name": "臺北市立聯合醫院-松德院區", "district": "中正區", "address": "金山南路一段5號" },
        { "name": "臺北市立聯合醫院-中醫昆明院區", "district": "萬華區", "address": "昆明街100號" },
        { "name": "臺北市立聯合醫院-林森院區", "district": "中山區", "address": "林森北路530號" },
        { "name": "臺北市立聯合醫院-陽明院區", "district": "士林區", "address": "雨聲街105號" },
        { "name": "臺北市立聯合醫院-忠孝院區", "district": "南港區", "address": "同德路87號" },
        { "name": "振興醫療財團法人振興醫院", "district": "北投區", "address": "振興街45號" },
        { "name": "中心診所醫療財團法人中心綜合醫院", "district": "大安區", "address": "忠孝東路四段77號" },
        { "name": "醫療財團法人辜公亮基金會和信治癌中心醫院", "district": "北投區", "address": "立德路125號" },
        { "name": "宏恩綜合醫院", "district": "大安區", "address": "仁愛路四段61號" },
        { "name": "康寧醫院", "district": "內湖區", "address": "成功路五段420巷26號" },
        { "name": "中國醫藥大學附設醫院-臺北分院", "district": "內湖區", "address": "內湖路二段360號" },
        { "name": "西園醫院", "district": "萬華區", "address": "西園路二段270號" },
        { "name": "博仁綜合醫院", "district": "松山區", "address": "光復北路66號" },
        { "name": "中山醫院", "district": "大安區", "address": "仁愛路四段112巷11號" },
        { "name": "尹書田紀念醫院", "district": "大安區", "address": "建國南路二段276號" },
        { "name": "衛生福利部臺北醫院-城區分院", "district": "大同區", "address": "鄭州路40號" },
        { "name": "協和婦女醫院", "district": "中山區", "address": "松江路85巷5號" },
        { "name": "景美醫院", "district": "文山區", "address": "羅斯福路六段280號" },
        { "name": "財團法人台灣省私立台北仁濟院附設仁濟醫院", "district": "萬華區", "address": "廣州街200號" },
        { "name": "台北市立關渡醫院（委託臺北榮民總醫院經營）", "district": "北投區", "address": "知行路225巷12號" },
        { "name": "秀傳醫院", "district": "大安區", "address": "光復南路116巷1號" },
        { "name": "泰安醫院", "district": "中山區", "address": "民權東路2段92巷2-1號" },
        { "name": "萬華醫院", "district": "萬華區", "address": "中華路二段606巷6號" }
    ],
    "新北市": [
        { "name": "汐止國泰綜合醫院", "district": "汐止區", "address": "建成路59巷2號" },
        { "name": "馬偕紀念醫院-淡水院區", "district": "淡水區", "address": "民生路45號" },
        { "name": "亞東紀念醫院", "district": "板橋區", "address": "南雅南路二段21號" },
        { "name": "天主教耕莘醫療財團法人耕莘醫院", "district": "新店區", "address": "中正路362號" },
        { "name": "耕莘醫院-安康院區", "district": "新店區", "address": "車子路15號" },
        { "name": "天主教永和耕莘醫院", "district": "永和區", "address": "中興街80號" },
        { "name": "新北市立聯合醫院-三重院區", "district": "三重區", "address": "新北大道一段3號" },
        { "name": "新北市立聯合醫院-板橋院區", "district": "板橋區", "address": "英士路198號" },
        { "name": "新北市立土城醫院", "district": "土城區", "address": "金城路二段6號" },
        { "name": "佛教慈濟醫療財團法人臺北慈濟醫院", "district": "新店區", "address": "建國路289號" },
        { "name": "衛生福利部雙和醫院", "district": "中和區", "address": "中正路291號" },
        { "name": "衛生福利部臺北醫院", "district": "新莊區", "address": "思源路127號" },
        { "name": "國立臺灣大學醫學院附設醫院-金山分院", "district": "金山區", "address": "玉爐路7號" },
        { "name": "行天宮醫療志業醫療財團法人恩主公醫院", "district": "三峽區", "address": "復興路399號" },
        { "name": "輔仁大學學校財團法人輔仁大學附設醫院", "district": "泰山區", "address": "貴子路69號" },
        { "name": "中英醫院", "district": "板橋區", "address": "文化路一段196號" },
        { "name": "板英醫院", "district": "板橋區", "address": "文化路一段269號" },
        { "name": "新仁醫院", "district": "新莊區", "address": "中正路395號" },
        { "name": "文化醫院", "district": "三峽區", "address": "介壽路一段199號" },
        { "name": "板新醫院", "district": "板橋區", "address": "中正路189號" },
        { "name": "蕭中正醫院", "district": "板橋區", "address": "南雅南路一段15之1號" },
        { "name": "板橋中興醫院", "district": "板橋區", "address": "忠孝路15號" },
        { "name": "板橋國泰醫院", "district": "板橋區", "address": "忠孝路5號" },
        { "name": "宏仁醫院", "district": "三重區", "address": "三和路二段188號" },
        { "name": "三重中興醫院", "district": "三重區", "address": "中興北街21號" },
        { "name": "祐民醫院", "district": "三重區", "address": "重新路二段2號" },
        { "name": "永和復康醫院", "district": "永和區", "address": "中和路575號" },
        { "name": "中祥醫院", "district": "中和區", "address": "中山路二段140號" },
        { "name": "怡和醫院", "district": "中和區", "address": "連成路49號" },
        { "name": "祥顥醫院", "district": "中和區", "address": "景平路412號" },
        { "name": "同仁醫院", "district": "新店區", "address": "民權路89號" },
        { "name": "新泰綜合醫院", "district": "新莊區", "address": "新樹路176號" },
        { "name": "益民醫院", "district": "新莊區", "address": "中港路127號" },
        { "name": "仁愛醫院", "district": "樹林區", "address": "文化街9號" },
        { "name": "公祥醫院", "district": "淡水區", "address": "中山路38號" },
        { "name": "瑞芳礦工醫院", "district": "瑞芳區", "address": "一坑路71之2號" },
        { "name": "廣川醫院", "district": "土城區", "address": "裕民路276號" },
        { "name": "仁安醫院", "district": "土城區", "address": "中央路一段62號" },
        { "name": "元復醫院", "district": "土城區", "address": "中央路二段318號" }
    ],
    "桃園市": [
        { "name": "林口長庚紀念醫院", "district": "龜山區", "address": "復興街5號" },
        { "name": "敏盛綜合醫院-經國總院", "district": "桃園區", "address": "經國路168號" },
        { "name": "敏盛綜合醫院-大園分院", "district": "大園區", "address": "華中街2號" },
        { "name": "敏盛綜合醫院-龍潭分院", "district": "龍潭區", "address": "中豐路168號" },
        { "name": "沙爾德聖保祿修女會醫療財團法人聖保祿醫院", "district": "桃園區", "address": "建新街123號" },
        { "name": "臺北榮民總醫院-桃園分院", "district": "桃園區", "address": "成功路三段100號" },
        { "name": "衛生福利部桃園醫院", "district": "桃園區", "address": "中山路1492號" },
        { "name": "國軍桃園總醫院附設民眾診療服務處", "district": "龍潭區", "address": "中興路168號" },
        { "name": "聯新國際醫院", "district": "平鎮區", "address": "廣泰路77號" },
        { "name": "怡仁綜合醫院", "district": "楊梅區", "address": "楊新北路321巷30號" },
        { "name": "天晟醫院", "district": "中壢區", "address": "延平路155號" },
        { "name": "振生醫院", "district": "桃園區", "address": "三民路二段288號" },
        { "name": "德濟醫院", "district": "八德區", "address": "介壽路二段77號" },
        { "name": "新國民醫院", "district": "中壢區", "address": "復興路152號" },
        { "name": "永康醫院", "district": "中壢區", "address": "裕民街13號" },
        { "name": "新永和醫院", "district": "平鎮區", "address": "延平路一段81號" },
        { "name": "天成醫院", "district": "楊梅區", "address": "中山北路一段356號" },
        { "name": "大明醫院", "district": "龜山區", "address": "萬壽路二段964號、966號" },
        { "name": "華揚醫院", "district": "中壢區", "address": "中北路二段316號" },
        { "name": "祐民醫院", "district": "中壢區", "address": "民族路二段180號" },
        { "name": "桃新醫院", "district": "桃園區", "address": "復興路195號" },
        { "name": "福太醫院", "district": "桃園區", "address": "民族路85號" },
        { "name": "德仁醫院", "district": "桃園區", "address": "桃鶯路245號" },
        { "name": "衛生福利部桃園醫院-新屋院區", "district": "新屋區", "address": "新褔二路6號" },
        { "name": "陽明醫院", "district": "平鎮區", "address": "延平路二段56號" },
        { "name": "宏其婦幼醫院", "district": "中壢區", "address": "元化路223號" },
        { "name": "承安醫院", "district": "中壢區", "address": "延平路643號" },
        { "name": "宋俊宏婦幼醫院", "district": "平鎮區", "address": "民族路199號" }
    ],
    "新竹市": [
        { "name": "馬偕紀念醫院-新竹分院", "district": "東區", "address": "光復路二段690號" },
        { "name": "國泰綜合醫院-新竹分院", "district": "東區", "address": "中華路二段678號" },
        { "name": "國立臺灣大學醫學院附設醫院-新竹分院", "district": "北區", "address": "經國路一段442巷25號" },
        { "name": "南門綜合醫院", "district": "東區", "address": "林森路20號" },
        { "name": "國軍新竹醫院", "district": "北區", "address": "武陵路3號" },
        { "name": "和平醫院", "district": "北區", "address": "和平路86-1號" },
        { "name": "台灣省私立桃園仁愛之家附設新生醫院", "district": "北區", "address": "西門街120號" },
        { "name": "新中興醫院", "district": "北區", "address": "興南街43號" },
        { "name": "惠民醫院", "district": "東區", "address": "民族路84之1號" }
    ],
    "新竹縣": [
        { "name": "東元醫療社團法人東元綜合醫院", "district": "竹北市", "address": "縣政二路69號" },
        { "name": "臺北榮民總醫院-新竹分院", "district": "竹東鎮", "address": "中豐路一段81號" },
        { "name": "中國醫藥大學新竹附設醫院", "district": "竹北市", "address": "興隆路一段199號" },
        { "name": "國立臺灣大學醫學院附設醫院新竹臺大分院生醫醫院-竹東院區", "district": "竹東鎮", "address": "至善路52號" },
        { "name": "國立臺灣大學醫學院附設醫院新竹臺大分院生醫醫院-竹北院區", "district": "竹北市", "address": "生醫路一段2號" },
        { "name": "天主教仁慈醫療財團法人仁慈醫院", "district": "湖口鄉", "address": "忠孝路29號" },
        { "name": "林醫院", "district": "竹東鎮", "address": "東林路76號" },
        { "name": "新仁醫院", "district": "竹北市", "address": "博愛街331號" },
        { "name": "竹信醫院", "district": "竹東鎮", "address": "仁愛路196號" },
        { "name": "黃醫院", "district": "竹東鎮", "address": "東寧路三段146號" },
        { "name": "大安醫院", "district": "竹北市", "address": "博愛街318巷6號" }
    ],
    "苗栗縣": [
        { "name": "為恭紀念醫院", "district": "頭份市", "address": "信義路128號" },
        { "name": "衛生福利部苗栗醫院", "district": "苗栗市", "address": "為公路747號" },
        { "name": "大千綜合醫院", "district": "苗栗市", "address": "恭敬路36號" },
        { "name": "李綜合醫療社團法人苑裡李綜合醫院", "district": "苑裡鎮", "address": "苑南里10鄰和平路168號" },
        { "name": "慈祐醫院", "district": "竹南鎮", "address": "民治街17號" },
        { "name": "大眾醫院", "district": "竹南鎮", "address": "光復路304號" },
        { "name": "協和醫院", "district": "苗栗市", "address": "中正路1367號" },
        { "name": "大川醫院", "district": "苗栗市", "address": "中正路416號" },
        { "name": "通霄光田醫院", "district": "通霄鎮", "address": "中山路88號" },
        { "name": "弘大醫院", "district": "苗栗市", "address": "新東街125號" },
        { "name": "財團法人台灣省私立桃園仁愛之家附設新竹新生醫院", "district": "苗栗市", "address": "新東街117號" },
        { "name": "大順醫院", "district": "大湖鄉", "address": "中正路48-5號" },
        { "name": "重光醫院", "district": "頭份市", "address": "中華路1039號" }
    ],
    "臺中市": [
        { "name": "臺中榮民總醫院", "district": "西屯區", "address": "臺灣大道4段1650號" },
        { "name": "中山醫學大學附設醫院", "district": "南區", "address": "建國北路一段110號" },
        { "name": "中山醫學大學附設醫院-中港院區", "district": "西區", "address": "台中港路1段23號" },
        { "name": "中國醫藥大學附設醫院", "district": "北區", "address": "育德路2號" },
        { "name": "衛生福利部豐原醫院", "district": "豐原區", "address": "安康路100號" },
        { "name": "衛生福利部臺中醫院", "district": "西區", "address": "三民路一段199號" },
        { "name": "童綜合醫院-本院", "district": "梧棲區", "address": "臺灣大道八段699號" },
        { "name": "童綜合醫院-沙鹿院區", "district": "沙鹿區", "address": "成功西街8號" },
        { "name": "台中慈濟醫院", "district": "潭子區", "address": "豐興路一段66號" },
        { "name": "國軍臺中總醫院-臺中總院", "district": "太平區", "address": "中山路二段348號" },
        { "name": "國軍臺中總醫院-中清院區", "district": "北區", "address": "忠明路500號" },
        { "name": "光田醫療社團法人光田綜合醫院-沙鹿總院", "district": "沙鹿區", "address": "沙田路117號" },
        { "name": "光田醫療社團法人光田綜合醫院-大甲分院", "district": "大甲區", "address": "經國路321號" },
        { "name": "童綜合醫療社團法人童綜合醫院", "district": "梧棲區", "address": "台灣大道八段699號" },
        { "name": "仁愛醫療財團法人台中仁愛醫院-大里院區", "district": "大里區", "address": "東榮路483號" },
        { "name": "仁愛醫療財團法人台中仁愛醫院-臺中院區", "district": "中區", "address": "柳川東路三段36號" },
        { "name": "李綜合醫療社團法人大甲李綜合醫院", "district": "大甲區", "address": "平安里12鄰八德街2號" },
        { "name": "澄清醫院-平等院區", "district": "中區", "address": "平等街139號" },
        { "name": "澄清醫院-中港院區", "district": "西屯區", "address": "臺灣大道四段118號" },
        { "name": "澄清醫院-敬德園區", "district": "西屯區", "address": "敬德街8號" },
        { "name": "澄清醫院-復健醫院", "district": "北屯區", "address": "太原路三段1142號" },
        { "name": "林新醫療社團法人林新醫院", "district": "南屯區", "address": "惠中路三段36號" },
        { "name": "林新醫療社團法人烏日林新醫院", "district": "烏日區", "address": "榮和路168號" },
        { "name": "陳芳英婦幼醫院", "district": "中區", "address": "平等街7號" },
        { "name": "聯安醫院", "district": "北屯區", "address": "東山路一段37號" },
        { "name": "新亞東婦產科醫院", "district": "北區", "address": "大雅路271號" },
        { "name": "林森醫院", "district": "西區", "address": "三民路一段152之1號" },
        { "name": "臺新醫院", "district": "東區", "address": "振興路441號" },
        { "name": "友仁醫院", "district": "南屯區", "address": "五權西路二段197號" },
        { "name": "宏恩醫院", "district": "南區", "address": "復興路二段38之13號" },
        { "name": "勝美醫院", "district": "北區", "address": "五權路482號" },
        { "name": "臺安醫院", "district": "東區", "address": "進化路203號" },
        { "name": "第一醫院", "district": "中區", "address": "民族路184號" },
        { "name": "中國醫藥大學附設醫院-臺中東區分院", "district": "東區", "address": "自由路三段296號" },
        { "name": "中國醫藥大學附設醫院-豐原分院", "district": "豐原區", "address": "中正路199號" },
        { "name": "全民醫院", "district": "北屯區", "address": "中清路72之42號" },
        { "name": "忠港醫院", "district": "梧棲區", "address": "中興路49號" },
        { "name": "順安醫院", "district": "大甲區", "address": "光明路6號" },
        { "name": "菩提醫院", "district": "大里區", "address": "中興路二段621號" },
        { "name": "達明眼科醫院", "district": "大里區", "address": "中興路二段490號" },
        { "name": "太平澄清醫院", "district": "太平區", "address": "中興路92號" },
        { "name": "烏日澄清醫院", "district": "烏日區", "address": "光明路419號" },
        { "name": "明德醫院", "district": "梧棲區", "address": "仁美街33巷50號" },
        { "name": "杏豐醫院", "district": "豐原區", "address": "三民路106號" },
        { "name": "漢忠醫院", "district": "豐原區", "address": "中正路218號" },
        { "name": "文化醫院", "district": "豐原區", "address": "園環東路721號" },
        { "name": "惠生醫院", "district": "豐原區", "address": "圓環北路一段319號" },
        { "name": "賢德醫院", "district": "太平區", "address": "宜昌路420號" },
        { "name": "東勢鎮農會附設農民醫院", "district": "東勢區", "address": "豐勢路297號" },
        { "name": "協和醫院", "district": "東勢區", "address": "豐勢路318號" },
        { "name": "豐安醫院", "district": "豐原區", "address": "中正路115號" },
        { "name": "清泉醫院", "district": "大雅區", "address": "雅潭路四段80號" },
        { "name": "霧峰澄清醫院", "district": "大里區", "address": "成功路55號" },
        { "name": "福平醫院", "district": "豐原區", "address": "中正路71號" },
        { "name": "祥恩醫院", "district": "豐原區", "address": "中興路35號" },
        { "name": "泰安醫院", "district": "霧峰區", "address": "中正路928號" },
        { "name": "本堂澄清醫院", "district": "霧峰區", "address": "中正路718號" },
        { "name": "仁美醫院", "district": "梧棲區", "address": "仁美街33巷48號" }
    ],
    "彰化縣": [
        { "name": "秀傳醫療財團法人彰濱秀傳紀念醫院", "district": "鹿港鎮", "address": "鹿工路6號" },
        { "name": "秀傳醫療社團法人秀傳紀念醫院", "district": "彰化市", "address": "中山路一段542號" },
        { "name": "彰化基督教醫療財團法人二林基督教醫院", "district": "二林鎮", "address": "大成路一段558號" },
        { "name": "彰化基督教醫療財團法人鹿港基督教醫院", "district": "鹿港鎮", "address": "中正路480號" },
        { "name": "彰化基督教醫療財團法人鹿東基督教醫院", "district": "鹿港鎮", "address": "鹿東路二段888號" },
        { "name": "彰化基督教醫療財團法人員林基督教醫院", "district": "員林市", "address": "莒光路456號" },
        { "name": "彰化基督教醫療財團法人彰化基督教醫院-南郭總院", "district": "彰化市", "address": "南校街135號" },
        { "name": "彰化基督教醫療財團法人彰化基督教醫院-中華路院區", "district": "彰化市", "address": "中華路176號" },
        { "name": "員生醫院", "district": "員林市", "address": "莒光路359號" },
        { "name": "漢銘醫院", "district": "彰化市", "address": "中山路一段366號" },
        { "name": "卓醫院", "district": "北斗鎮", "address": "中山路一段311號" },
        { "name": "秀傳醫療體系仁和醫院", "district": "田中鎮", "address": "中州路一段157號" },
        { "name": "宗生醫院", "district": "秀水鄉", "address": "埔崙村彰水路2段195號" },
        { "name": "顏國湖醫院", "district": "和美鎮", "address": "彰美路五段301號" },
        { "name": "員榮醫療社團法人員榮醫院", "district": "員林市", "address": "中正路201號" },
        { "name": "員林何醫院", "district": "員林市", "address": "民族街33號" },
        { "name": "張天長醫院", "district": "員林市", "address": "員水路二段482號" },
        { "name": "協和醫院", "district": "員林市", "address": "惠來街98號" },
        { "name": "英仁醫院", "district": "埤頭鄉", "address": "斗苑西路277號" },
        { "name": "信生醫院", "district": "彰化市", "address": "民生里三民路312號" },
        { "name": "衛生福利部彰化醫院", "district": "埔心鄉", "address": "中正路二段80號" },
        { "name": "黃俊榮醫院", "district": "彰化市", "address": "信義里中正路一段432號" },
        { "name": "順安醫院", "district": "彰化市", "address": "光復路53號" },
        { "name": "建元醫院", "district": "田中鎮", "address": "中南路三段512號" },
        { "name": "伸港忠孝醫院", "district": "伸港鄉", "address": "忠孝路30號" },
        { "name": "道周醫療社團法人道周醫院", "district": "和美鎮", "address": "和光路180號" },
        { "name": "員郭醫院", "district": "員林市", "address": "員林大道六段51號" },
        { "name": "冠華醫院", "district": "彰化市", "address": "中正路一段367號" },
        { "name": "長森醫院", "district": "彰化市", "address": "磚瑤里彰草路425號" },
        { "name": "南星醫院", "district": "北斗鎮", "address": "居仁里斗苑路一段26號" },
        { "name": "惠來醫療社團法人宏仁醫院", "district": "員林市", "address": "惠來街89號" },
        { "name": "婦友醫院", "district": "彰化市", "address": "中山路二段487號" },
        { "name": "洪宗鄰醫院", "district": "二林鎮", "address": "中正路61號" },
        { "name": "宋志懿醫院", "district": "二林鎮", "address": "豐田裡大成路一段51號" }
    ],
    "雲林縣": [
        { "name": "國立臺灣大學醫學院附設醫院雲林分院-斗六院區", "district": "斗六市", "address": "雲林路二段579號" },
        { "name": "國立臺灣大學醫學院附設醫院雲林分院-虎尾院區", "district": "虎尾鎮", "address": "廉使里19鄰學府路95號" },
        { "name": "國立成功大學醫學院附設醫院斗六分院", "district": "斗六市", "address": "莊敬路345號" },
        { "name": "中國醫藥大學北港附設醫院", "district": "北港鎮", "address": "新德路123號" },
        { "name": "彰化基督教醫院雲林分院", "district": "西螺鎮", "address": "市場南路375號" },
        { "name": "天主教若瑟醫療財團法人若瑟醫院", "district": "虎尾鎮", "address": "新生路74號" },
        { "name": "長庚醫療財團法人雲林長庚紀念醫院", "district": "麥寮鄉", "address": "中興村工業路1500號" },
        { "name": "佛教慈濟醫療財團法人斗六慈濟醫院", "district": "斗六市", "address": "雲林路二段248號" },
        { "name": "蔡醫院", "district": "土庫鎮", "address": "中山路64號" },
        { "name": "安生醫院", "district": "斗六市", "address": "永樂街120號" },
        { "name": "天主教福安醫院", "district": "斗南鎮", "address": "北銘里文昌路110號" },
        { "name": "全生醫院", "district": "北港鎮", "address": "中正路100號" },
        { "name": "全民醫院", "district": "台西鄉", "address": "中山路391號" },
        { "name": "三仁醫院", "district": "褒忠鄉", "address": "中正路466號" },
        { "name": "洪揚醫院", "district": "斗六市", "address": "文化路138號" },
        { "name": "元吉醫院", "district": "斗六市", "address": "民生路82號" },
        { "name": "諸元內科醫院", "district": "北港鎮", "address": "中和里中山路125號" },
        { "name": "婦友醫院", "district": "北港鎮", "address": "華勝里公園路155號" },
        { "name": "育仁醫院", "district": "西螺鎮", "address": "延平路162號" },
        { "name": "雲林華濟醫院", "district": "崙背鄉", "address": "大有村286號" }
    ],
    "南投縣": [
        { "name": "南投基督教醫院", "district": "南投市", "address": "中興路870號" },
        { "name": "佑民醫療社團法人佑民醫院", "district": "草屯鎮", "address": "太平路一段200號" },
        { "name": "衛生福利部南投醫院-院本部", "district": "南投市", "address": "復興路478號" },
        { "name": "衛生福利部南投醫院-中興院區", "district": "南投市", "address": "環山路57號" },
        { "name": "竹山秀傳醫院", "district": "竹山鎮", "address": "集山路二段75號" },
        { "name": "埔里基督教醫院", "district": "埔里鎮", "address": "鐵山路1號" },
        { "name": "臺中榮民總醫院埔里分院", "district": "埔里鎮", "address": "中山路三段339號" },
        { "name": "中國醫藥大學附設醫院-草屯分院（惠和醫院）", "district": "草屯鎮", "address": "平等街140號" },
        { "name": "東華醫院", "district": "竹山鎮", "address": "集山路三段272巷16號" },
        { "name": "曾漢棋綜合醫院", "district": "草屯鎮", "address": "虎山路915號" },
        { "name": "新泰宜婦幼醫院", "district": "名間鄉", "address": "彰南路571號之1" }
    ],
    "嘉義市": [
        { "name": "嘉義基督教醫院-總院", "district": "東區", "address": "忠孝路539號" },
        { "name": "嘉義基督教醫院-保康生活園區", "district": "東區", "address": "保順路121號" },
        { "name": "天主教聖馬爾定醫院-大雅總院", "district": "東區", "address": "大雅路二段565號" },
        { "name": "天主教聖馬爾定醫院-民權院區", "district": "東區", "address": "民權路60號" },
        { "name": "天主教聖馬爾定醫院-芳安院區", "district": "東區", "address": "芳安路103號" },
        { "name": "臺中榮民總醫院嘉義分院", "district": "西區", "address": "世賢路二段600號" },
        { "name": "衛生福利部嘉義醫院", "district": "西區", "address": "北港路312號" },
        { "name": "陽明醫院", "district": "東區", "address": "吳鳯北路252號" },
        { "name": "祥太醫院", "district": "西區", "address": "延平街490號永和街116號" },
        { "name": "慶昇醫院", "district": "西區", "address": "新榮路339-1號" },
        { "name": "盧亞人醫院", "district": "西區", "address": "民權路406號" },
        { "name": "陳仁德醫院", "district": "西區", "address": "林森西路285號" },
        { "name": "安心醫院", "district": "西區", "address": "新民路88號" },
        { "name": "世華醫院", "district": "西區", "address": "仁愛路365號" }
    ],
    "嘉義縣": [
        { "name": "佛教慈濟醫療財團法人大林慈濟醫院", "district": "大林鎮", "address": "民生路2號" },
        { "name": "長庚醫療財團法人嘉義長庚紀念醫院", "district": "朴子市", "address": "嘉朴路西段6號" },
        { "name": "衛生福利部朴子醫院", "district": "朴子市", "address": "永和里42-50號" },
        { "name": "臺中榮民總醫院灣橋分院", "district": "竹崎鄉", "address": "灣橋村石麻園38號" },
        { "name": "和順興醫院", "district": "民雄鄉", "address": "民族路49號" },
        { "name": "新仁友醫院", "district": "中埔鄉", "address": "和睦村中華路398號" }
    ],
    "臺南市": [
        { "name": "國立成功大學醫學院附設醫院", "district": "北區", "address": "勝利路138號" },
        { "name": "奇美醫院-永康總院", "district": "永康區", "address": "中華路901號" },
        { "name": "奇美醫院-樹林院區", "district": "南區", "address": "樹林街二段442號" },
        { "name": "柳營奇美醫院", "district": "柳營區", "address": "太康里13鄰太康201號" },
        { "name": "佳里奇美醫院", "district": "佳里區", "address": "佳興里6鄰佳里興606號" },
        { "name": "臺南市立醫院", "district": "東區", "address": "崇德路670號" },
        { "name": "臺南市立安南醫院", "district": "安南區", "address": "州南里長和路二段66號" },
        { "name": "台灣基督長老教會新樓醫療財團法人麻豆新樓醫院", "district": "東區", "address": "東門路一段57號" },
        { "name": "郭綜合醫院", "district": "中西區", "address": "民生路二段22號" },
        { "name": "衛生福利部臺南醫院-臺南總院", "district": "中西區", "address": "中山路125號" },
        { "name": "衛生福利部臺南醫院-新化分院", "district": "新化區", "address": "那拔里牧場72號" },
        { "name": "衛生福利部胸腔病院", "district": "仁德區", "address": "中山路864號" },
        { "name": "衛生福利部新營醫院", "district": "新營區", "address": "信義街73號" },
        { "name": "仁愛醫療社團法人仁愛醫院", "district": "東區", "address": "北門路一段10號" },
        { "name": "洪外科醫院", "district": "中西區", "address": "民生路二段60號" },
        { "name": "永川醫院", "district": "中西區", "address": "成功路169號" },
        { "name": "永和醫院", "district": "中西區", "address": "府前路一段310號" },
        { "name": "鄭和燃醫院", "district": "中西區", "address": "忠義路二段225號" },
        { "name": "仁村醫院", "district": "中西區", "address": "西門路一段486號" },
        { "name": "陳志誠耳鼻喉科醫院", "district": "北區", "address": "公園路315-1號" },
        { "name": "開元寺慈愛醫院", "district": "北區", "address": "北園街89－1號" },
        { "name": "仁仁醫院", "district": "中西區", "address": "運河南街3號" },
        { "name": "郭明慧醫院", "district": "中西區", "address": "中正路324號1樓" },
        { "name": "周宗盛醫院", "district": "東區", "address": "莊敬路100號" },
        { "name": "麻豆新樓醫院", "district": "麻豆區", "address": "麻佳路一段207號" },
        { "name": "高雄榮民總醫院臺南分院", "district": "永康區", "address": "復興路427號" },
        { "name": "仁慈醫院", "district": "仁德區", "address": "中正路二段1225號" },
        { "name": "連婦產科醫院", "district": "永康區", "address": "中山南路29號" },
        { "name": "王建章婦產科醫院", "district": "永康區", "address": "中華路580號" },
        { "name": "盈泰中西醫聯合診所", "district": "關廟區", "address": "中正路1023號" },
        { "name": "宏科醫院", "district": "善化區", "address": "三民路1-35號" },
        { "name": "永達醫院", "district": "永康區", "address": "永大路二段1326號" },
        { "name": "新生醫院", "district": "佳里區", "address": "新生路272號" },
        { "name": "蓋德醫院", "district": "六甲區", "address": "中正路178之1號" },
        { "name": "新興醫院", "district": "新營區", "address": "中興路10號" },
        { "name": "佑昇醫院", "district": "白河區", "address": "民安路1號" }
    ],
    "高雄市": [
        { "name": "高雄榮民總醫院", "district": "左營區", "address": "大中一路386號" },
        { "name": "高雄長庚紀念醫院", "district": "鳥松區", "address": "大埤路123號" },
        { "name": "高雄醫學大學附設中和紀念醫院", "district": "三民區", "address": "自由一路100號" },
        { "name": "國軍高雄總醫院左營分院附設民眾診療服務處", "district": "苓雅區", "address": "中正一路2號" },
        { "name": "高雄市立凱旋醫院", "district": "苓雅區", "address": "凱旋二路130號" },
        { "name": "高雄市立聯合醫院", "district": "鼓山區", "address": "中華一路976號" },
        { "name": "高雄市立民生醫院", "district": "苓雅區", "address": "凱旋二路134號" },
        { "name": "高雄市立小港醫院", "district": "小港區", "address": "山明路482號" },
        { "name": "高雄市立大同醫院", "district": "前金區", "address": "中華三路68號" },
        { "name": "高雄市立鳳山醫院", "district": "鳳山區", "address": "經武路42號" },
        { "name": "高雄市立旗津醫院", "district": "旗津區", "address": "旗港路33號" },
        { "name": "高雄市立岡山醫院", "district": "岡山區", "address": "壽天路12號" },
        { "name": "義大醫療財團法人義大醫院", "district": "燕巢區", "address": "義大路1號" },
        { "name": "義大醫療財團法人義大癌治療醫院", "district": "燕巢區", "address": "義大路21號" },
        { "name": "義大醫療財團法人義大大昌醫院", "district": "三民區", "address": "大昌一路305號" },
        { "name": "阮綜合醫療社團法人阮綜合醫院", "district": "苓雅區", "address": "成功一路162號" },
        { "name": "天主教聖功醫院", "district": "苓雅區", "address": "建國一路352號" },
        { "name": "健仁醫院", "district": "楠梓區", "address": "楠陽路136號" },
        { "name": "段志憲婦產科醫院", "district": "前金區", "address": "七賢二路347號" },
        { "name": "德謙醫院", "district": "三民區", "address": "九如二路18號" },
        { "name": "民族婦產科家醫科醫院", "district": "三民區", "address": "民族一路880號" },
        { "name": "聖新醫院", "district": "三民區", "address": "自立一路336號" },
        { "name": "謝外科醫院", "district": "三民區", "address": "河北一路330號" },
        { "name": "南山醫院", "district": "三民區", "address": "建國三路151號" },
        { "name": "祐生醫院", "district": "三民區", "address": "建國三路60號" },
        { "name": "永仁醫院", "district": "三民區", "address": "鳳南里建國三路415號" },
        { "name": "文雄醫院", "district": "三民區", "address": "察哈爾二街132號" },
        { "name": "乃榮醫院", "district": "苓雅區", "address": "三多二路226號" },
        { "name": "臨海醫院", "district": "小港區", "address": "沿海一路461號" },
        { "name": "重仁骨科醫院", "district": "前金區", "address": "中華三路243號" },
        { "name": "榮生醫院", "district": "左營區", "address": "實踐路51號" },
        { "name": "愛仁醫院", "district": "三民區", "address": "民族一路51號" },
        { "name": "吉田耳鼻喉科醫院", "district": "前金區", "address": "自強一路61號" },
        { "name": "二聖醫院", "district": "前鎮區", "address": "二聖一路71號" },
        { "name": "瑞祥醫院", "district": "前鎮區", "address": "班超路92號" },
        { "name": "協和醫院", "district": "前鎮區", "address": "崗山南路470號" },
        { "name": "五塊厝醫院", "district": "苓雅區", "address": "三多一路139號" },
        { "name": "太順醫院", "district": "苓雅區", "address": "大順三路178號" },
        { "name": "博正醫院", "district": "左營區", "address": "修明街69號" },
        { "name": "聖明醫院", "district": "鼓山區", "address": "鼓山三路52號" },
        { "name": "三泰醫院", "district": "鼓山區", "address": "九如四路1030號" },
        { "name": "三民建國醫院", "district": "鼓山區", "address": "中華一路345號" },
        { "name": "柯醫院", "district": "鼓山區", "address": "臨海二路37號" },
        { "name": "新高鳳醫院", "district": "鳳山區", "address": "光遠路360號" },
        { "name": "全民醫院", "district": "三民區", "address": "九如二路501號" },
        { "name": "吳昆哲婦產小兒科醫院", "district": "前鎮區", "address": "民權二路430號" },
        { "name": "邱綜合醫院", "district": "苓雅區", "address": "成功一路137號" },
        { "name": "高雄基督教信義醫院", "district": "苓雅區", "address": "華新街86號" },
        { "name": "蕭志文醫院", "district": "新興區", "address": "七賢一路102號" },
        { "name": "惠仁醫院", "district": "新興區", "address": "中山一路67之2號" },
        { "name": "長春醫院", "district": "楠梓區", "address": "右昌街331號" },
        { "name": "顏威裕醫院", "district": "楠梓區", "address": "後昌路826號" },
        { "name": "林進興醫院", "district": "三民區", "address": "九如一路200號" },
        { "name": "安泰醫院", "district": "小港區", "address": "學府路111號" },
        { "name": "馨蕙馨醫院", "district": "左營區", "address": "明誠二路541號" },
        { "name": "聖和醫院", "district": "前金區", "address": "青年二路6號" },
        { "name": "健生醫院", "district": "三民區", "address": "九如二路68號" },
        { "name": "正大醫院", "district": "鼓山區", "address": "鼓山三路128號" },
        { "name": "佳欣婦幼醫院", "district": "前鎮區", "address": "三多三路149號" },
        { "name": "新石津醫院", "district": "鳳山區", "address": "自強二路112號" },
        { "name": "佛公醫院", "district": "前鎮區", "address": "后安路263號" },
        { "name": "戴浚銘婦兒醫院", "district": "小港區", "address": "宏平路661號" },
        { "name": "柏仁醫院", "district": "左營區", "address": "博愛二路350號" },
        { "name": "國軍高雄總醫院岡山分院", "district": "岡山區", "address": "大義二路1號" },
        { "name": "劉嘉修醫院", "district": "岡山區", "address": "岡山路428號" },
        { "name": "李明達醫院", "district": "岡山區", "address": "岡山路74號" },
        { "name": "惠川醫院", "district": "岡山區", "address": "岡山路92號" },
        { "name": "劉光雄醫院", "district": "岡山區", "address": "岡山路380-1號" },
        { "name": "萬民醫院", "district": "阿蓮區", "address": "中山路71號" },
        { "name": "三聖骨科醫院", "district": "美濃區", "address": "合和路56號" },
        { "name": "高新醫院", "district": "路竹區", "address": "中山路627號" },
        { "name": "溫有諒醫院", "district": "路竹區", "address": "延平路57號" },
        { "name": "重安醫院", "district": "旗山區", "address": "大仁街18號" },
        { "name": "旗山博愛醫院", "district": "旗山區", "address": "延平一路689號" },
        { "name": "大東醫院", "district": "鳳山區", "address": "光遠路171-2號" },
        { "name": "優生婦產科醫院", "district": "鳳山區", "address": "自由路189號" },
        { "name": "泰和醫院", "district": "橋頭區", "address": "成功路101號" },
        { "name": "峰田醫院", "district": "岡山區", "address": "岡山路530號" },
        { "name": "建佑醫院", "district": "林園區", "address": "東林西路360號" },
        { "name": "廣聖醫院", "district": "旗山區", "address": "中華路618號" },
        { "name": "衛生福利部旗山醫院", "district": "旗山區", "address": "中學路60號" },
        { "name": "溪洲醫院", "district": "旗山區", "address": "延平一路412號" },
        { "name": "樂生婦幼醫院", "district": "大寮區", "address": "鳳林三路532號" },
        { "name": "惠德醫院", "district": "鳳山區", "address": "福祥街81號" },
        { "name": "仁惠婦幼醫院", "district": "鳳山區", "address": "自由路81號" },
        { "name": "橋頭社區醫院", "district": "橋頭區", "address": "成功路8號" },
        { "name": "鴻慶醫院", "district": "大寮區", "address": "九和路5號" },
        { "name": "宏亞醫院", "district": "鳳山區", "address": "五甲三路14號" }
    ],
    "屏東縣": [
        { "name": "衛生福利部屏東醫院", "district": "屏東市", "address": "自由路270號" },
        { "name": "屏基醫療財團法人屏東基督教醫院", "district": "屏東市", "address": "大連路60號" },
        { "name": "安泰醫療社團法人安泰醫院", "district": "東港鎮", "address": "中正路一段210號" },
        { "name": "寶建醫療社團法人寶建醫院", "district": "屏東市", "address": "中山路123號" },
        { "name": "恆基醫療財團法人恆春基督教醫院", "district": "恆春鎮", "address": "恆西路21號" },
        { "name": "屏東民眾醫院", "district": "屏東市", "address": "忠孝路120-1號" },
        { "name": "安和醫療社團法人安和醫院", "district": "屏東市", "address": "自由路598號" },
        { "name": "輔英科技大學附設醫院", "district": "東港鎮", "address": "中山路5號" },
        { "name": "國軍高雄總醫院屏東分院", "district": "屏東市", "address": "大湖路58巷22號" },
        { "name": "高雄榮民總醫院屏東分院", "district": "內埔鄉", "address": "昭勝路安平1巷1號" },
        { "name": "枋寮醫院", "district": "枋寮鄉", "address": "中山路139號" },
        { "name": "李澤醫院", "district": "東港鎮", "address": "中山路36號" },
        { "name": "復興醫院", "district": "屏東市", "address": "民生路147之3號" },
        { "name": "國仁醫院", "district": "屏東市", "address": "民生東路12-2號" },
        { "name": "衛生福利部恆春旅遊醫院", "district": "恆春鎮", "address": "恆南路188號" },
        { "name": "恆春南門醫院", "district": "恆春鎮", "address": "南門路10號" },
        { "name": "大新醫院", "district": "高樹鄉", "address": "興中路208號" },
        { "name": "潮州安泰醫院", "district": "潮州鎮", "address": "四維路162號" },
        { "name": "優生婦產科醫院", "district": "屏東市", "address": "瑞光路三段103號" },
        { "name": "六愛醫院", "district": "潮州鎮", "address": "中山路168號" },
        { "name": "皇安醫療社團法人小康醫院", "district": "新埤鄉", "address": "新華路文化巷18-1號" },
        { "name": "茂隆骨科醫院", "district": "潮州鎮", "address": "朝昇路322號" },
        { "name": "林連風醫院", "district": "屏東市", "address": "民權路46號" }
    ],
    "宜蘭縣": [
        { "name": "天主教靈醫會羅東聖母醫院", "district": "羅東鎮", "address": "中正南路160號" },
        { "name": "羅許基金會羅東博愛醫院", "district": "羅東鎮", "address": "南昌街81、83號、站前南路61、63號" },
        { "name": "國立陽明交通大學附設醫院-蘭陽院區", "district": "宜蘭市", "address": "校舍路169號" },
        { "name": "國立陽明交通大學附設醫院-新民院區", "district": "宜蘭市", "address": "新民路152號" },
        { "name": "臺北榮民總醫院-蘇澳分院", "district": "蘇澳鎮", "address": "蘇濱路一段301號" },
        { "name": "臺北榮民總醫院-員山分院", "district": "員山鄉", "address": "內城村榮光路386號" },
        { "name": "蘭陽仁愛醫院", "district": "宜蘭市", "address": "中山路二段260號" },
        { "name": "杏和醫院", "district": "礁溪鄉", "address": "礁溪路四段129號" },
        { "name": "建生醫院", "district": "蘇澳鎮", "address": "中山路一段218號" },
        { "name": "佛教普門醫院", "district": "宜蘭市", "address": "尚深路91號" }
    ],
    "花蓮縣": [
        { "name": "佛教慈濟醫療財團法人花蓮慈濟醫院", "district": "花蓮市", "address": "中央路三段707號" },
        { "name": "佛教慈濟醫療財團法人玉里慈濟醫院", "district": "玉里鎮", "address": "民權街1-1號" },
        { "name": "衛生福利部花蓮醫院", "district": "花蓮市", "address": "中正路600號" },
        { "name": "衛生福利部花蓮醫院-豐濱分院", "district": "豐濱鄉", "address": "光豐路41號" },
        { "name": "國軍花蓮總醫院附設民眾診療服務處", "district": "新城鄉", "address": "嘉里路163號" },
        { "name": "臺灣基督教門諾會醫療財團法人門諾醫院", "district": "花蓮市", "address": "民權路44號" },
        { "name": "臺北榮民總醫院-鳳林分院", "district": "鳳林鎮", "address": "中正路一段2號" },
        { "name": "臺北榮民總醫院-玉里分院", "district": "玉里鎮", "address": "新興街91號" }
    ],
    "臺東縣": [
        { "name": "馬偕紀念醫院-臺東分院", "district": "臺東市", "address": "長沙街303巷1號" },
        { "name": "衛生福利部臺東醫院-總院", "district": "臺東市", "address": "五權街1號" },
        { "name": "衛生福利部臺東醫院-成功分院", "district": "成功鎮", "address": "中山東路32號" },
        { "name": "臺北榮民總醫院-臺東分院", "district": "臺東市", "address": "更生路1000號" },
        { "name": "佛教慈濟醫療財團法人關山慈濟醫院", "district": "關山鎮", "address": "和平路125之5號" },
        { "name": "台東聖母醫院", "district": "臺東市", "address": "杭州街2號" },
        { "name": "台東基督教醫院", "district": "臺東市", "address": "開封街350號" },
        { "name": "仁和醫院", "district": "太麻里鄉", "address": "太麻里街265號" }
    ],
    "澎湖縣": [
        { "name": "三軍總醫院-澎湖分院", "district": "馬公市", "address": "前寮里90號" },
        { "name": "衛生福利部澎湖醫院", "district": "馬公市", "address": "中正路10號" },
        { "name": "天主教惠民醫院", "district": "馬公市", "address": "樹德路14號" }
    ],
    "金門縣": [
        { "name": "衛生福利部金門醫院", "district": "金湖鎮", "address": "新市里復興路2號" },
        { "name": "衛生福利部金門醫院-烈嶼院區", "district": "烈嶼鄉", "address": "後井37號" }
    ],
    "連江縣": [
        { "name": "連江縣立醫院", "district": "南竿鄉", "address": "復興村217號" }
    ]
};

const distData = {
    "基隆市": [
        "仁愛區", "中正區", "信義區", "中山區", "安樂區", "暖暖區", "七堵區"
    ],
    "臺北市": [
        "中正區", "大同區", "中山區", "萬華區", "信義區", "松山區", "大安區", "南港區", "北投區", "內湖區", "士林區", "文山區"
    ],
    "新北市": [
        "板橋區", "新莊區", "泰山區", "林口區", "淡水區", "金山區", "八里區", "萬里區", "石門區", "三芝區", "瑞芳區", "汐止區", "平溪區", "貢寮區", "雙溪區", "深坑區", "石碇區", "新店區", "坪林區", "烏來區", "中和區", "永和區", "土城區", "三峽區", "樹林區", "鶯歌區", "三重區", "蘆洲區", "五股區"
    ],
    "桃園市": [
        "桃園區", "中壢區", "平鎮區", "八德區", "楊梅區", "蘆竹區", "龜山區", "龍潭區", "大溪區", "大園區", "觀音區", "新屋區", "復興區"
    ],
    "新竹市": [
        "東區", "北區", "香山區"
    ],
    "新竹縣": [
        "竹北市", "竹東鎮", "新埔鎮", "關西鎮", "峨眉鄉", "寶山鄉", "北埔鄉", "橫山鄉", "芎林鄉", "湖口鄉", "新豐鄉", "尖石鄉", "五峰鄉"
    ],
    "苗栗縣": [
        "苗栗市", "通霄鎮", "苑裡鎮", "竹南鎮", "頭份鎮", "後龍鎮", "卓蘭鎮", "西湖鄉", "頭屋鄉", "公館鄉", "銅鑼鄉", "三義鄉", "造橋鄉", "三灣鄉", "南庄鄉", "大湖鄉", "獅潭鄉", "泰安鄉"
    ],
    "臺中市": [
        "中區", "東區", "南區", "西區", "北區", "北屯區", "西屯區", "南屯區", "太平區", "大里區", "霧峰區", "烏日區", "豐原區", "后里區", "東勢區", "石岡區", "新社區", "和平區", "神岡區", "潭子區", "大雅區", "大肚區", "龍井區", "沙鹿區", "梧棲區", "清水區", "大甲區", "外埔區", "大安區"
    ],
    "彰化縣": [
        "彰化市", "員林鎮", "和美鎮", "鹿港鎮", "溪湖鎮", "二林鎮", "田中鎮", "北斗鎮", "花壇鄉", "芬園鄉", "大村鄉", "永靖鄉", "伸港鄉", "線西鄉", "福興鄉", "秀水鄉", "埔心鄉", "埔鹽鄉", "大城鄉", "芳苑鄉", "竹塘鄉", "社頭鄉", "二水鄉", "田尾鄉", "埤頭鄉", "溪州鄉"
    ],
    "雲林縣": [
        "斗六市", "斗南鎮", "虎尾鎮", "西螺鎮", "土庫鎮", "北港鎮", "莿桐鄉", "林內鄉", "古坑鄉", "大埤鄉", "崙背鄉", "二崙鄉", "麥寮鄉", "臺西鄉", "東勢鄉", "褒忠鄉", "四湖鄉", "口湖鄉", "水林鄉", "元長鄉"
    ],
    "南投縣": [
        "南投市", "埔里鎮", "草屯鎮", "竹山鎮", "集集鎮", "名間鄉", "鹿谷鄉", "中寮鄉", "魚池鄉", "國姓鄉", "水里鄉", "信義鄉", "仁愛鄉"
    ],
    "嘉義市": [
        "東區", "西區"
    ],
    "嘉義縣": [
        "太保市", "朴子市", "布袋鎮", "大林鎮", "民雄鄉", "溪口鄉", "新港鄉", "六腳鄉", "東石鄉", "義竹鄉", "鹿草鄉", "水上鄉", "中埔鄉", "竹崎鄉", "梅山鄉", "番路鄉", "大埔鄉", "阿里山鄉"
    ],
    "臺南市": [
        "中西區", "東區", "南區", "北區", "安平區", "安南區", "永康區", "歸仁區", "新化區", "左鎮區", "玉井區", "楠西區", "南化區", "仁德區", "關廟區", "龍崎區", "官田區", "麻豆區", "佳里區", "西港區", "七股區", "將軍區", "學甲區", "北門區", "新營區", "後壁區", "白河區", "東山區", "六甲區", "下營區", "柳營區", "鹽水區", "善化區", "大內區", "山上區", "新市區", "安定區"
    ],
    "高雄市": [
        "楠梓區", "左營區", "鼓山區", "三民區", "鹽埕區", "前金區", "新興區", "苓雅區", "前鎮區", "旗津區", "小港區", "鳳山區", "林園區", "大寮區", "大樹區", "大社區", "仁武區", "鳥松區", "岡山區", "橋頭區", "燕巢區", "田寮區", "阿蓮區", "路竹區", "湖內區", "茄萣區", "永安區", "彌陀區", "梓官區", "旗山區", "美濃區", "六龜區", "甲仙區", "杉林區", "內門區", "茂林區", "桃源區", "那瑪夏區"
    ],
    "屏東縣": [
        "屏東市", "潮州鎮", "東港鎮", "恆春鎮", "萬丹鄉", "長治鄉", "麟洛鄉", "九如鄉", "里港鄉", "鹽埔鄉", "高樹鄉", "萬巒鄉", "內埔鄉", "竹田鄉", "新埤鄉", "枋寮鄉", "新園鄉", "崁頂鄉", "林邊鄉", "南州鄉", "佳冬鄉", "琉球鄉", "車城鄉", "滿州鄉", "枋山鄉", "三地門鄉", "霧臺鄉", "瑪家鄉", "泰武鄉", "來義鄉", "春日鄉", "獅子鄉", "牡丹鄉"
    ],
    "宜蘭縣": [
        "宜蘭市", "羅東鎮", "蘇澳鎮", "頭城鎮", "礁溪鄉", "壯圍鄉", "員山鄉", "冬山鄉", "五結鄉", "三星鄉", "大同鄉", "南澳鄉"
    ],
    "花蓮縣": [
        "花蓮市", "鳳林鎮", "玉里鎮", "新城鄉", "吉安鄉", "壽豐鄉", "光復鄉", "豐濱鄉", "瑞穗鄉", "富里鄉", "秀林鄉", "萬榮鄉", "卓溪鄉"
    ],
    "臺東縣": [
        "臺東市", "成功鎮", "關山鎮", "卑南鄉", "鹿野鄉", "池上鄉", "東河鄉", "長濱鄉", "太麻里鄉", "大武鄉", "綠島鄉", "海端鄉", "延平鄉", "金峰鄉", "達仁鄉", "蘭嶼鄉"
    ],
    "澎湖縣": [
        "馬公市", "湖西鄉", "白沙鄉", "西嶼鄉", "望安鄉", "七美鄉"
    ],
    "金門縣": [
        "金沙鎮", "金湖鎮", "金寧鄉", "金城鎮", "烈嶼鄉", "烏坵鄉"
    ],
    "連江縣": [
        "南竿鄉", "北竿鄉", "莒光鄉", "東引鄉"
    ]
};